name: Build Nuitka (Windows)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
        packages: write
        contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nuitka

      - name: Build with Nuitka
        shell: pwsh
        run: |
            $assets = python -c "import pjsk_background_gen_PIL, os; print(os.path.join(os.path.dirname(pjsk_background_gen_PIL.__file__), 'assets'))"
            python -m nuitka --assume-yes-for-downloads --onefile --standalone --python-flag=-OO --follow-imports --remove-output --lto=yes --no-pyi-file "--include-data-dir=$assets=pjsk_background_gen_PIL/assets" main.py


      - name: Rename and zip file
        shell: pwsh
        run: |
            Rename-Item -Path main.exe -NewName ChartDownloader.exe
            Compress-Archive -Path ChartDownloader.exe -DestinationPath ChartDownloader.zip

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ChartDownloader ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }} - Generated with Nuitka"
          files: ./ChartDownloader.zip
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}